/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address 
 * @param id 
 * @param metadata 
 * @param port 
 */


data class CtlPeer (

    @Json(name = "Address")
    val address: kotlin.String? = null,

    @Json(name = "Id")
    val id: kotlin.String? = null,

    @Json(name = "Metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "Port")
    val port: kotlin.Int? = null

) {


}

