/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.IdmPolicyCondition
import org.sinou.pydia.openapi.model.IdmPolicyEffect

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actions 
 * @param conditions 
 * @param description 
 * @param effect 
 * @param id 
 * @param resources 
 * @param subjects 
 */


data class IdmPolicy (

    @Json(name = "actions")
    val actions: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "conditions")
    val conditions: kotlin.collections.Map<kotlin.String, IdmPolicyCondition>? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "effect")
    val effect: IdmPolicyEffect? = IdmPolicyEffect.unknown,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "resources")
    val resources: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "subjects")
    val subjects: kotlin.collections.List<kotlin.String>? = null

) {


}

