/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.InstallInstallConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param config 
 * @param name 
 */


data class InstallPerformCheckRequest (

    @Json(name = "Config")
    val config: InstallInstallConfig? = null,

    @Json(name = "Name")
    val name: kotlin.String? = null

) {


}

