/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.InstallHeaderModAction
import org.sinou.pydia.openapi.model.InstallHeaderModApplyTo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action 
 * @param applyTo 
 * @param key 
 * @param `value` 
 */


data class InstallHeaderMod (

    @Json(name = "Action")
    val action: InstallHeaderModAction? = InstallHeaderModAction.APPEND_IF_EXISTS_OR_ADD,

    @Json(name = "ApplyTo")
    val applyTo: InstallHeaderModApplyTo? = InstallHeaderModApplyTo.REQUEST,

    @Json(name = "Key")
    val key: kotlin.String? = null,

    @Json(name = "Value")
    val `value`: kotlin.String? = null

) {


}

