/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.InstallTLSCertificate
import org.sinou.pydia.openapi.model.InstallTLSLetsEncrypt
import org.sinou.pydia.openapi.model.InstallTLSSelfSigned

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param binds 
 * @param certificate 
 * @param letsEncrypt 
 * @param maintenance 
 * @param maintenanceConditions 
 * @param reverseProxyURL 
 * @param ssLRedirect 
 * @param selfSigned 
 */


data class InstallProxyConfig (

    @Json(name = "Binds")
    val binds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "Certificate")
    val certificate: InstallTLSCertificate? = null,

    @Json(name = "LetsEncrypt")
    val letsEncrypt: InstallTLSLetsEncrypt? = null,

    @Json(name = "Maintenance")
    val maintenance: kotlin.Boolean? = null,

    @Json(name = "MaintenanceConditions")
    val maintenanceConditions: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "ReverseProxyURL")
    val reverseProxyURL: kotlin.String? = null,

    @Json(name = "SSLRedirect")
    val ssLRedirect: kotlin.Boolean? = null,

    @Json(name = "SelfSigned")
    val selfSigned: InstallTLSSelfSigned? = null

) {


}

