/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.JobsTaskStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param jobId 
 * @param pruneLimit 
 * @param status 
 * @param taskID 
 */


data class JobsDeleteTasksRequest (

    @Json(name = "JobId")
    val jobId: kotlin.String? = null,

    @Json(name = "PruneLimit")
    val pruneLimit: kotlin.Int? = null,

    @Json(name = "Status")
    val status: kotlin.collections.List<JobsTaskStatus>? = null,

    @Json(name = "TaskID")
    val taskID: kotlin.collections.List<kotlin.String>? = null

) {


}

