/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param address 
 * @param language 
 * @param name 
 * @param uuid 
 */


data class MailerUser (

    @Json(name = "Address")
    val address: kotlin.String? = null,

    @Json(name = "Language")
    val language: kotlin.String? = null,

    @Json(name = "Name")
    val name: kotlin.String? = null,

    @Json(name = "Uuid")
    val uuid: kotlin.String? = null

)

