/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.IdmACL

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param acLs 
 * @param total 
 */


data class RestACLCollection (

    @Json(name = "ACLs")
    val acLs: kotlin.collections.List<IdmACL>? = null,

    @Json(name = "Total")
    val total: kotlin.Int? = null

) {


}

