/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.RestSettingsEntry

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param CHILDREN 
 * @param DESCRIPTION 
 * @param key 
 * @param LABEL 
 */


data class RestSettingsSection (

    @Json(name = "CHILDREN")
    val CHILDREN: kotlin.collections.List<RestSettingsEntry>? = null,

    @Json(name = "DESCRIPTION")
    val DESCRIPTION: kotlin.String? = null,

    @Json(name = "Key")
    val key: kotlin.String? = null,

    @Json(name = "LABEL")
    val LABEL: kotlin.String? = null

) {


}

