/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientID 
 * @param path 
 */


data class RestDocumentAccessTokenRequest (

    @Json(name = "ClientID")
    val clientID: kotlin.String? = null,

    @Json(name = "Path")
    val path: kotlin.String? = null

) {


}

