/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.RestShareLink

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createPassword 
 * @param passwordEnabled 
 * @param shareLink 
 * @param updateCustomHash 
 * @param updatePassword 
 */


data class RestPutShareLinkRequest (

    @Json(name = "CreatePassword")
    val createPassword: kotlin.String? = null,

    @Json(name = "PasswordEnabled")
    val passwordEnabled: kotlin.Boolean? = null,

    @Json(name = "ShareLink")
    val shareLink: RestShareLink? = null,

    @Json(name = "UpdateCustomHash")
    val updateCustomHash: kotlin.String? = null,

    @Json(name = "UpdatePassword")
    val updatePassword: kotlin.String? = null

) {


}

