/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param category 
 * @param description 
 * @param formModule 
 * @param formModuleProps 
 * @param hasForm 
 * @param icon 
 * @param inputDescription 
 * @param isInternal If action is declared internal, it is hidden to avoid polluting the list.
 * @param label 
 * @param name 
 * @param outputDescription 
 * @param summaryTemplate 
 * @param tint 
 */


data class RestActionDescription (

    @Json(name = "Category")
    val category: kotlin.String? = null,

    @Json(name = "Description")
    val description: kotlin.String? = null,

    @Json(name = "FormModule")
    val formModule: kotlin.String? = null,

    @Json(name = "FormModuleProps")
    val formModuleProps: kotlin.String? = null,

    @Json(name = "HasForm")
    val hasForm: kotlin.Boolean? = null,

    @Json(name = "Icon")
    val icon: kotlin.String? = null,

    @Json(name = "InputDescription")
    val inputDescription: kotlin.String? = null,

    /* If action is declared internal, it is hidden to avoid polluting the list. */
    @Json(name = "IsInternal")
    val isInternal: kotlin.Boolean? = null,

    @Json(name = "Label")
    val label: kotlin.String? = null,

    @Json(name = "Name")
    val name: kotlin.String? = null,

    @Json(name = "OutputDescription")
    val outputDescription: kotlin.String? = null,

    @Json(name = "SummaryTemplate")
    val summaryTemplate: kotlin.String? = null,

    @Json(name = "Tint")
    val tint: kotlin.String? = null

) {


}

