/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.IdmWorkspace

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param workspaces 
 * @param workspacesAccesses 
 */


data class RestUserStateResponse (

    @Json(name = "Workspaces")
    val workspaces: kotlin.collections.List<IdmWorkspace>? = null,

    @Json(name = "WorkspacesAccesses")
    val workspacesAccesses: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

