/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param details 
 * @param status 
 */


data class RestComponentStatus (

    @Json(name = "Details")
    val details: kotlin.String? = null,

    @Json(name = "Status")
    val status: kotlin.String? = null

) {


}

