/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path 
 * @param wsLabel 
 * @param wsScope 
 * @param wsSlug 
 * @param wsUuid 
 */


data class TreeWorkspaceRelativePath (

    @Json(name = "Path")
    val path: kotlin.String? = null,

    @Json(name = "WsLabel")
    val wsLabel: kotlin.String? = null,

    @Json(name = "WsScope")
    val wsScope: kotlin.String? = null,

    @Json(name = "WsSlug")
    val wsSlug: kotlin.String? = null,

    @Json(name = "WsUuid")
    val wsUuid: kotlin.String? = null

) {


}

