/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: unknown,idle,running,finished,interrupted,paused,any,error,queued
 */

@JsonClass(generateAdapter = false)
enum class JobsTaskStatus(val value: kotlin.String) {

    @Json(name = "Unknown")
    unknown("Unknown"),

    @Json(name = "Idle")
    idle("Idle"),

    @Json(name = "Running")
    running("Running"),

    @Json(name = "Finished")
    finished("Finished"),

    @Json(name = "Interrupted")
    interrupted("Interrupted"),

    @Json(name = "Paused")
    paused("Paused"),

    @Json(name = "Any")
    any("Any"),

    @Json(name = "Error")
    error("Error"),

    @Json(name = "Queued")
    queued("Queued");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JobsTaskStatus) "$data" else null

        /**
         * Returns a valid [JobsTaskStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JobsTaskStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

