/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.IdmWorkspace

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total 
 * @param workspaces 
 */


data class RestWorkspaceCollection (

    @Json(name = "Total")
    val total: kotlin.Int? = null,

    @Json(name = "Workspaces")
    val workspaces: kotlin.collections.List<IdmWorkspace>? = null

)

