/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.CtlService

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param services 
 * @param total 
 */


data class RestServiceCollection (

    @Json(name = "Services")
    val services: kotlin.collections.List<CtlService>? = null,

    @Json(name = "Total")
    val total: kotlin.Int? = null

)

