/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.ProtobufAny
import org.sinou.pydia.openapi.model.ServiceOperationType
import org.sinou.pydia.openapi.model.ServiceResourcePolicyQuery

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit 
 * @param offset 
 * @param operation 
 * @param resourcePolicyQuery 
 * @param subQueries 
 * @param groupBy 
 */


data class ServiceQuery (

    @Json(name = "Limit")
    val limit: kotlin.String? = null,

    @Json(name = "Offset")
    val offset: kotlin.String? = null,

    @Json(name = "Operation")
    val operation: ServiceOperationType? = ServiceOperationType.oR,

    @Json(name = "ResourcePolicyQuery")
    val resourcePolicyQuery: ServiceResourcePolicyQuery? = null,

    @Json(name = "SubQueries")
    val subQueries: kotlin.collections.List<ProtobufAny>? = null,

    @Json(name = "groupBy")
    val groupBy: kotlin.Int? = null

)

