/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.TreeNode
import org.sinou.pydia.openapi.model.TreeNodeChangeEventEventType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param metadata 
 * @param optimistic 
 * @param silent 
 * @param source 
 * @param target 
 * @param type 
 */


data class TreeNodeChangeEvent (

    @Json(name = "Metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "Optimistic")
    val optimistic: kotlin.Boolean? = null,

    @Json(name = "Silent")
    val silent: kotlin.Boolean? = null,

    @Json(name = "Source")
    val source: TreeNode? = null,

    @Json(name = "Target")
    val target: TreeNode? = null,

    @Json(name = "Type")
    val type: TreeNodeChangeEventEventType? = TreeNodeChangeEventEventType.CREATE

)

