/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.TreeChangeLog
import org.sinou.pydia.openapi.model.TreeNodeType
import org.sinou.pydia.openapi.model.TreeWorkspaceRelativePath

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param appearsIn 
 * @param commits 
 * @param etag 
 * @param mtime 
 * @param metaStore 
 * @param mode 
 * @param path 
 * @param propertySize 
 * @param type 
 * @param uuid 
 */


data class TreeNode (

    @Json(name = "AppearsIn")
    val appearsIn: List<TreeWorkspaceRelativePath>? = null,

    @Json(name = "Commits")
    val commits: List<TreeChangeLog>? = null,

    @Json(name = "Etag")
    val etag: String? = null,

    @Json(name = "MTime")
    val mtime: String? = null,

    @Json(name = "MetaStore")
    val metaStore: Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "Mode")
    val mode: Int? = null,

    @Json(name = "Path")
    val path: kotlin.String? = null,

    @Json(name = "Size")
    val propertySize: kotlin.String? = null,

    @Json(name = "Type")
    val type: TreeNodeType? = TreeNodeType.UNKNOWN,

    @Json(name = "Uuid")
    val uuid: kotlin.String? = null

)

