/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.ActivityStreamContext
import org.sinou.pydia.openapi.model.ActivitySummaryPointOfView

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param asDigest 
 * @param boxName 
 * @param context 
 * @param contextData 
 * @param language Provide language information for building the human-readable strings.
 * @param limit 
 * @param offset 
 * @param pointOfView 
 * @param streamFilter 
 * @param unreadCountOnly 
 */


data class ActivityStreamActivitiesRequest (

    @Json(name = "AsDigest")
    val asDigest: kotlin.Boolean? = null,

    @Json(name = "BoxName")
    val boxName: kotlin.String? = null,

    @Json(name = "Context")
    val context: ActivityStreamContext? = ActivityStreamContext.mYFEED,

    @Json(name = "ContextData")
    val contextData: kotlin.String? = null,

    /* Provide language information for building the human-readable strings. */
    @Json(name = "Language")
    val language: kotlin.String? = null,

    @Json(name = "Limit")
    val limit: kotlin.String? = null,

    @Json(name = "Offset")
    val offset: kotlin.String? = null,

    @Json(name = "PointOfView")
    val pointOfView: ActivitySummaryPointOfView? = ActivitySummaryPointOfView.gENERIC,

    @Json(name = "StreamFilter")
    val streamFilter: kotlin.String? = null,

    @Json(name = "UnreadCountOnly")
    val unreadCountOnly: kotlin.Boolean? = null

)

