/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.IdmACLAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ACL are the basic flags that can be put anywhere in the tree to provide some specific rights to a given role. The context of how they apply can be fine-tuned by workspace.
 *
 * @param action 
 * @param ID 
 * @param nodeID 
 * @param roleID 
 * @param workspaceID 
 */


data class IdmACL (

    @Json(name = "Action")
    val action: IdmACLAction? = null,

    @Json(name = "ID")
    val ID: kotlin.String? = null,

    @Json(name = "NodeID")
    val nodeID: kotlin.String? = null,

    @Json(name = "RoleID")
    val roleID: kotlin.String? = null,

    @Json(name = "WorkspaceID")
    val workspaceID: kotlin.String? = null

)

