/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: lOCAL,s3,sMB,cELLS,aZURE,gCS,b2,mANTA,sIA
 */

@JsonClass(generateAdapter = false)
enum class ObjectStorageType(val value: kotlin.String) {

    @Json(name = "LOCAL")
    lOCAL("LOCAL"),

    @Json(name = "S3")
    s3("S3"),

    @Json(name = "SMB")
    sMB("SMB"),

    @Json(name = "CELLS")
    cELLS("CELLS"),

    @Json(name = "AZURE")
    aZURE("AZURE"),

    @Json(name = "GCS")
    gCS("GCS"),

    @Json(name = "B2")
    b2("B2"),

    @Json(name = "MANTA")
    mANTA("MANTA"),

    @Json(name = "SIA")
    sIA("SIA");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ObjectStorageType) "$data" else null

        /**
         * Returns a valid [ObjectStorageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ObjectStorageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

