/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param advertiseIp 
 * @param hostname 
 * @param ips 
 * @param machine 
 */


data class RegistryNode (

    @Json(name = "advertiseIp")
    val advertiseIp: kotlin.String? = null,

    @Json(name = "hostname")
    val hostname: kotlin.String? = null,

    @Json(name = "ips")
    val ips: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "machine")
    val machine: kotlin.String? = null

)

