/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.ObjectDataSource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bucketsRegexp 
 * @param dataSource 
 */


data class RestListStorageBucketsRequest (

    @Json(name = "BucketsRegexp")
    val bucketsRegexp: kotlin.String? = null,

    @Json(name = "DataSource")
    val dataSource: ObjectDataSource? = null

)

