/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allMetaProviders 
 * @param filters 
 * @param limit 
 * @param nodePaths 
 * @param offset 
 * @param sortDirDesc 
 * @param sortField 
 * @param versions 
 */


data class RestGetBulkMetaRequest (

    @Json(name = "AllMetaProviders")
    val allMetaProviders: kotlin.Boolean? = null,

    @Json(name = "Filters")
    val filters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "Limit")
    val limit: kotlin.Int? = null,

    @Json(name = "NodePaths")
    val nodePaths: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "Offset")
    val offset: kotlin.Int? = null,

    @Json(name = "SortDirDesc")
    val sortDirDesc: kotlin.Boolean? = null,

    @Json(name = "SortField")
    val sortField: kotlin.String? = null,

    @Json(name = "Versions")
    val versions: kotlin.Boolean? = null

)

