/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.sinou.pydia.openapi.model

import org.sinou.pydia.openapi.model.ProtobufAny

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param details 
 * @param message 
 */


data class RpcStatus (

    @Json(name = "code")
    val code: kotlin.Int? = null,

    @Json(name = "details")
    val details: kotlin.collections.List<ProtobufAny>? = null,

    @Json(name = "message")
    val message: kotlin.String? = null

)

